### PR TITLE
For #7: Added game scene

### PR DESCRIPTION
**Pull request by paulodamaso**
For #7: Added game scene

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#37](https://github.com/enigmadragons/projectneon/issues/37) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#37](https://github.com/enigmadragons/projectneon/issues/37); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@SilasReinagel Done, please take a look

**Comment by 0crat** [comment]
The job [#37](https://github.com/enigmadragons/projectneon/issues/37) is now out of scope

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#37` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Pull request merged**
