### PR TITLE
For #27: Created Deck and Card classes, and shuffle() method for Deck…

### LINKED ISSUE #27: Battle Setup: 1. Shuffle player deck, and each individual enemy deck
Role: DEV

### PR DESCRIPTION
**Pull request by paulodamaso**
Closes #27: Created Deck and Card classes, and shuffle() method for Deck Class

### CODE REVIEW

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#75](https://github.com/enigmadragons/projectneon/issues/75) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) everybody who has role `REV` is banned at [#75](https://github.com/enigmadragons/projectneon/issues/75); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@SilasReinagel 1 & 2 have been solved, please take a look. As for 3, is not clear to me where should I use these created classes

**Comment by SilasReinagel** [comment]
@paulodamaso Decks should be shuffled in Battle Setup. So if you setup a GameObject in BattleScene with a Start method who shuffles the party deck and enemy decks, that should work well.

You can create test decks with 2-8 blank cards, and assign them in the editor to your Shuffle Cards script.

**Comment by paulodamaso** [comment]
@SilasReinagel I've created `BattleSetup` object, which shuffles player and enemy decks, please take a look

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#75` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#75](https://github.com/enigmadragons/projectneon/issues/75) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Pull request merged**
