### PR TITLE
For #283: Clicking on Card on list view should put it on main pane, a…

### LINKED ISSUE #283: Obsolete: DeckBuilder: Add/Remove Cards From Current Deck
Clicking on a card in the main pane, should add a copy to the Deck list.

Clicking on a card in the Decklist should remove one copy of that card, and put a copy back in the Main Pane.

Deck changes should persist. 

Estimate: 2 units

### PR DESCRIPTION
**Pull request by paulodamaso**
Closes #283: Clicking on Card on list view should put it on main pane, and vice-versa

- Created `ListToDeck` and `DeckToList` methods, which gets the card from one place and puis into another. These methods are supposed to be called by `CardSelector` by the clicked entity (`CardBg` or `CardListItem`) passing its internal `Card` reference.

### CODE REVIEW

**Comment by SilasReinagel** [comment]
@paulodamaso The ticket talks all about clicking. I don't see anything related to Clicking on the UI in this PR.

**Comment by SilasReinagel** [comment]
@paulodamaso If we need other work, let's make a new ticket and put the correct work with the correct ticket. 

#283 should just be about clicking interactions in the UI working.

**Comment by paulodamaso** [comment]
@SilasReinagel Done, please take a look.

Libraryview is already sepparated as a prefab, please take a look to the picture below:

image

**Comment by paulodamaso** [comment]
@SilasReinagel Conflicts solved, please take a look

**Comment by paulodamaso** [comment]
@SilasReinagel This PR rot and now it's harder to  fix it than make it again. I'm closing it

**Pull request closed without merging**
