### PR TITLE
For #102: Advance battle phase to resolution phase

### LINKED ISSUE #102: puzzles.md:8: Battle Phase should advance to Resolution...
The puzzle `1-5dd07971` from EnigmaDragons/ProjectNeon#1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/576113e803b84e8cd8475554c3f909ecbec03227/puzzles.md#L8-L8

The puzzle was created by Silas Reinagel on 17-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by paulodamaso**
Closes #102:

- Created Resolution element, with EventOrchestrator triggered upon PLayerTurnConfirm and EnemyTurnsConfirm

### CODE REVIEW

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#196](https://github.com/enigmadragons/projectneon/issues/196) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) everybody who has role `REV` is banned at [#196](https://github.com/enigmadragons/projectneon/issues/196); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by SilasReinagel** [comment]
@paulodamaso There is a different bug. If `EventOrchestrator` requires 0 events, then he never triggers. Later, we will have to make it trigger `OnStart` in that scenario. 

If that were happening, then `TurnResolutionFinished` would happen even before Battle Setup is finished. But we can address all of that in a different ticket.

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#196` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#196](https://github.com/enigmadragons/projectneon/issues/196) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Pull request merged**
