### PR TITLE
For #28: Player party setup

### LINKED ISSUE #28: Battle Setup: Player's party characters are shown on the left-side of the screen in traditional JRPG battle view
Use greybox character squares for now, or placeholder images.

### PR DESCRIPTION
**Pull request by paulodamaso**
Closes #28: Player party setup

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#92](https://github.com/enigmadragons/projectneon/issues/92) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) everybody who has role `REV` is banned at [#92](https://github.com/enigmadragons/projectneon/issues/92); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@SilasReinagel Fixed 1 erasing all dead code. Found that I forgot to put the method in right  place (`Start`), made that, 2 and 3 are corrected too. I couldn't understand comment 5, I did exactly what you asked me (`BattleSetup` was already  in the project; I've created `BattlePlayerPartySetup` just to avoid coupling).

Just 4 seems cryptic to me: I'm still not very fluent in creating the classes / objects / whatever and wiring them all to create a test scene

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#92` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#92](https://github.com/enigmadragons/projectneon/issues/92) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Pull request merged**
