### PR TITLE
Move cards down after finishing selection. Closes #133

### LINKED ISSUE #133: Once all Cards Selected, hide the hand, and move all Play Zone cards to Resolution Area
See this video: https://youtu.be/xMrdxMn7wN0?t=164
Once Player and Enemy have selected their Cards:
- Hide the player hand.
- Move all card from the Player Play Zone to the Resolution Zone
- Resolution Zone should be visible at the bottom of the screen

### PR DESCRIPTION
**Pull request by WhimsySoftware**

### CODE REVIEW

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#176](https://github.com/enigmadragons/projectneon/issues/176) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) everybody who has role `REV` is banned at [#176](https://github.com/enigmadragons/projectneon/issues/176); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by SilasReinagel** [comment]
@WhimsySoftware This branch still have unrelated files, and merge conflicts.

**Pull request closed without merging**
