### PR TITLE
For #6: Title screen sketch

### PR DESCRIPTION
**Pull request by paulodamaso**
For #6: Title screen sketch

- added title screen
- left puzzles for continuing development

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#36](https://github.com/enigmadragons/projectneon/issues/36) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#36](https://github.com/enigmadragons/projectneon/issues/36); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@SilasReinagel Done, please take a look

**Comment by SilasReinagel** [comment]
@paulodamaso Comment for future reference. Make folder based on feature for Prefabs. Don't put prefabs in folders with other feature names.

PR is good enough for now.

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#36` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#36](https://github.com/enigmadragons/projectneon/issues/36) is now out of scope

**Pull request merged**
