### PR TITLE
For #208: Changed Character to Hero

### PR DESCRIPTION
**Pull request by paulodamaso**
Closes#208: Changed `Character` references to `Hero`

Change character in cs files and unity elements to hero.

I've noticed that we have to set the same property a lot of times for Heroes, in different elements: bust, Hero objects, etc. Is that right?

### CODE REVIEW

**Comment by SilasReinagel** [comment]
This looks great. There is one conflict due to your previous PR. This this can be merged.

**Comment by SilasReinagel** [comment]
@paulodamaso What about the same property? I'm not clear on this question.

> I've noticed that we have to set the same property a lot of times for Heroes, in different elements: bust, Hero objects, etc. Is that right?

**Comment by paulodamaso** [comment]
@SilasReinagel I don't recall exacly where, but i had to set hero inside a some objects; then set her Bust inside other ones; But I think that we should get the bust value from Hero instance (in Party), and don't set it directly right?

**Comment by SilasReinagel** [comment]
@paulodamaso If you are thinking about `PartyVisualizer` it does only read the busts. Also, some thing will change once we have more DragonBones models. Busts will only be used in some places. 

Bust should be editor-only configurable though. If you find any write access to Hero busts, lock it down.

**Comment by paulodamaso** [comment]
@SilasReinagel Conflicts resolved, please take a look

**Comment by SilasReinagel** [comment]
@paulodamaso This one still has a couple of broken things. It's going to be hard to ever merge though, so I'm going to merge it and fix it afterwards.

**Pull request merged**
