### PR TITLE
Closes #59: Created Navigator class and added navigation to all scene…

### LINKED ISSUE #59: Setup Button Navigation between All Scenes
Add all game scenes to the build.
Handle navigation via Events.

Use methods or string mapping for navigation, not numeric references.

Blocked by #11 and #12.

### PR DESCRIPTION
**Pull request by paulodamaso**
Closes #59: Created Navigator class and added navigation to all scene buttons

- Added `Navigator.cs`
- Wired navigation through `Navigator.cs` to all scenes

### CODE REVIEW

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#74](https://github.com/enigmadragons/projectneon/issues/74) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) everybody who has role `REV` is banned at [#74](https://github.com/enigmadragons/projectneon/issues/74); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@SilasReinagel Done, please take  a look

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#74` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#74](https://github.com/enigmadragons/projectneon/issues/74) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Pull request merged**
