### PR TITLE
Added Event Guide. Closes #116

### LINKED ISSUE #116: Create Event Tutorial

### PR DESCRIPTION
**Pull request by SilasReinagel**

### CODE REVIEW

**Comment by SilasReinagel** [comment]
@paulodamaso This Event guide has been created.

**Comment by 0crat** [comment]
Job [#117](https://github.com/enigmadragons/projectneon/issues/117) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#117` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#117](https://github.com/enigmadragons/projectneon/issues/117) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Pull request merged**
